import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        black: {
          900: "#07090B",
          800: "#11171D",
          700: "#1A2126",
          600: "#333E46",
          500: "#3A4850",
          400: "#727F86",
          300: "#9EA8AD",
          200: "#B7BFC2",
          100: "#D8DBDC",
        },
        red: {
          900: "#AF0008",
          800: "#C3001C",
          700: "#D3002C",
          600: "#FF1F29",
          500: "#FF545C",
          400: "#FF9297",
          300: "#FFBFC2",
          200: "#FFDCDE",
          100: "#FFEFF0",
        },
        surface: {
          900: "#698AAE",
          800: "#7996B7",
          700: "#8AA3C0",
          600: "#9DB2CA",
          500: "#B1C2D5",
          400: "#C5D2E0",
          300: "#DBE3EC",
          200: "#EBF0F5",
          100: "#F3F6F9",
        },
        neutral: {
          900: "#212529",
          800: "#343A40",
          700: "#495057",
          600: "#868E96",
          500: "#ADB5BD",
          400: "#CED4DA",
          300: "#DEE2E6",
          200: "#F1F3F5",
          100: "#FFFFFF",
        },
        green: {
          900: "#00392B",
          800: "#004D3A",
          700: "#006049",
          600: "#007358",
          500: "#008566",
          400: "#33AB8C",
          300: "#66CAAE",
          200: "#99E2CD",
          100: "#E0F0ED",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
